name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Install NPM dependencies 📦
        uses: bahmutov/npm-install@v1

      - name: Unit tests 🧪
        run: npm test

     
      - name: Check totals 🛡
        run: node bin/check-total --min 30

      - name: Set commit status using REST
        # https://developer.github.com/v3/repos/statuses/
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
                "state": "success",
                "description": "REST commit status",
                "context": "a test"
              }'

      - name: Set code coverage commit status 📫
        run: node bin/set-gh-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check coverage change from README 📫
        run: node bin/set-gh-status --check-against-readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update code coverage badge 🥇
        run: node bin/update-badge

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v3
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
