name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Install NPM dependencies 📦
        uses: bahmutov/npm-install@v1

      - name: Check all covered files 📊
        run: |
          node bin/check-coverage main1.js
          node bin/check-coverage to/main2.js
          node bin/only-covered main1.js main2.js

      - name: Check totals 🛡
        run: node bin/check-total --min 90

      - name: Update code coverage badge 🥇
        run: node bin/update-badge

      - name: Set commit status using REST
        # https://developer.github.com/v3/repos/statuses/
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
                "state": "success",
                "description": "REST status 📯",
                "context": "a test"
              }'

      - name: Set commit status 📫
        # variables available in GitHub container by default
        # https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
        # https://developer.github.com/v3/activity/events/types/#statusevent
        # state: pending | success | failure | error
        run: |
          npx octokit repos create-status \
            --owner bahmutov \
            --repo check-code-coverage \
            --state success \
            --sha $GITHUB_SHA \
            --context "Testing status"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
